export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const DISPLAYED_USER = "DISPLAYED_USER";

export const FETCHED_COLLECTIONS = "FETCHED_COLLECTIONS";
export const COLLECTIONS_UPDATED = "COLLECTIONS_UPDATED";
export const UPDATE_HANDLED = "UPDATE_HANDLED";